spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #url: jdbc:mysql://10.110.68.31:30062/icp_native?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      #username: native
      #password: 123456aB
      url: jdbc:mysql://117.73.8.191:3306/mydb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 199412Ab
  jpa:
     show-sql: true
  redis:
    database: 0
    host: 192.168.40.130
    port: 6379
  #spring.redis.password=
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
    connect-timeout: 1000


